name: flutter_programming_test
description: Flutter Programming Test.

publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_it: ^7.6.0
  sqflite: ^2.2.8+4
  get_storage: ^2.1.1
  flutter_localization: ^0.1.8
  shimmer: ^3.0.0
  dropdown_button2: ^2.1.3
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
